stages:
  ingest:
    cmd: python -m src.components.data_ingestion
    deps:
      - src/components/data_ingestion.py
      - data/raw/daily_forex_rates.csv
    params:
      - data
      - cleaning
    outs:
      - artifacts/clean.parquet

  transform:
    cmd: python -m src.components.data_transformation
    deps:
      - src/components/data_transformation.py
      - artifacts/clean.parquet
    params:
      - features
    outs:
      - artifacts/features.parquet

      